### ISSUE TITLE
/lib/linux/arm/libunwind.a missing

### ISSUE THREAD

**Issue by VanHoevenTR** [bluesadi/Pluto-Obfuscator#13]
I try to install pluto obfuscator in Android NDK 23 by following this step https://github.com/o2e/OLLVM-9.0.1#%E6%95%B4%E5%90%88%E5%88%B0ndk but i'm getting error 

```
C:\Users\uwu\AppData\Local\Android\Sdk\ndk\23.0.7599858\ndk-build
fcntl(): Bad file descriptor
Android NDK: APP_PLATFORM not set. Defaulting to minimum supported version android-16.
Android NDK: WARNING: APP_PLATFORM android-16 is higher than android:minSdkVersion 1 in ./AndroidManifest.xml. NDK binaries will *not* be compatible with devices older than android-16. See https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md for more information.
Android NDK: ERROR:C:/Users/uwu/AppData/Local/Android/Sdk/ndk/23.0.7599858/build//../sources/cxx-stl/llvm-libc++abi/Android.mk:unwind: LOCAL_SRC_FILES points to a missing file
Android NDK: Check that /lib/linux/arm/libunwind.a exists  or that its path is correct
C:/Users/uwu/AppData/Local/Android/Sdk/ndk/23.0.7599858/build//../build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
```

I read this issue to solve, so the directory become `C:\Users\uwu\AppData\Local\Android\Sdk\ndk\23.0.7599858\toolchains\llvm\prebuilt\windows-x86_64\lib\clang\12.0.1\lib\linux\arm ` but still getting same error
https://github.com/heroims/obfuscator/issues/7#issuecomment-1025939903

What i'm missing?

Can you upgrade llvm to 12.0.5 by any change?

**Comment by bluesadi** [comment]
I have embeded the pluto obfuscator in NDK 23 successfully in this way: https://bbs.pediy.com/thread-271271.htm

Maybe you can have a try.

**Comment by VanHoevenTR** [comment]
Ok, i'll try it out

**Comment by VanHoevenTR** [comment]
@bluesadi i'm getting an error while running build.py. I'm using Linux mint 20.3 based on Ubuntu 20.04.4 and i'm on step 3. Compile the llvm-android source code / 3. 编译 llvm-android 源代码 

```
DEBUG:utils:subprocess.run:17:12:19 /home/linux/llvm-toolchain/prebuilts/build-tools/linux-x86/bin/ninja
[6/2000] Linking CXX shared library li...libclang_rt.ubsan_standalone-x86_64.so
clang-12: warning: argument unused during compilation: '-static-libstdc++' [-Wunused-command-line-argument]
[7/2000] Linking CXX shared library li...lib/linux/libclang_rt.hwasan-x86_64.so
clang-12: warning: argument unused during compilation: '-static-libstdc++' [-Wunused-command-line-argument]
[8/2000] Linking CXX shared library li...ib/linux/libclang_rt.memprof-x86_64.so
clang-12: warning: argument unused during compilation: '-static-libstdc++' [-Wunused-command-line-argument]
[9/2000] Linking CXX shared library li...8/lib/linux/libclang_rt.asan-x86_64.so
clang-12: warning: argument unused during compilation: '-static-libstdc++' [-Wunused-command-line-argument]
[20/2000] Building CXX object tools/cl...gDynamicASTMatchers.dir/Registry.cpp.o
FAILED: tools/clang/lib/ASTMatchers/Dynamic/CMakeFiles/obj.clangDynamicASTMatchers.dir/Registry.cpp.o 
/home/linux/llvm-toolchain/prebuilts/clang/host/linux-x86/clang-bootstrap/bin/clang++ --sysroot=/home/linux/llvm-toolchain/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/sysroot -DCLANG_REPOSITORY_STRING=\"https://android.googlesource.com/toolchain/llvm-project\" -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Itools/clang/lib/ASTMatchers/Dynamic -I/home/linux/llvm-toolchain/out/llvm-project/clang/lib/ASTMatchers/Dynamic -I/home/linux/llvm-toolchain/out/llvm-project/clang/include -Itools/clang/include -Iinclude -I/home/linux/llvm-toolchain/out/llvm-project/llvm/include -ffile-prefix-map=/home/linux/llvm-toolchain/= -B/home/linux/llvm-toolchain/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/x86_64-linux/bin -stdlib=libc++ -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wstring-conversion -fdiagnostics-color -ffunction-sections -fdata-sections -fexperimental-new-pass-manager -fno-common -Woverloaded-virtual -Wno-nested-anon-types -O3 -DNDEBUG -fPIC  -fno-exceptions -fno-rtti -std=c++14 -MD -MT tools/clang/lib/ASTMatchers/Dynamic/CMakeFiles/obj.clangDynamicASTMatchers.dir/Registry.cpp.o -MF tools/clang/lib/ASTMatchers/Dynamic/CMakeFiles/obj.clangDynamicASTMatchers.dir/Registry.cpp.o.d -o tools/clang/lib/ASTMatchers/Dynamic/CMakeFiles/obj.clangDynamicASTMatchers.dir/Registry.cpp.o -c /home/linux/llvm-toolchain/out/llvm-project/clang/lib/ASTMatchers/Dynamic/Registry.cpp
Killed
[25/2000] Building CXX object tools/cl...Files/obj.clangSema.dir/SemaExpr.cpp.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/linux/llvm-toolchain/toolchain/llvm_android/do_build.py", line 768, in <module>
    main()
  File "/home/linux/llvm-toolchain/toolchain/llvm_android/do_build.py", line 678, in main
    stage1.build()
  File "/home/linux/llvm-toolchain/toolchain/llvm_android/builder_registry.py", line 67, in wrapper
    function(builder, *args, **kwargs)
  File "/home/linux/llvm-toolchain/toolchain/llvm_android/base_builders.py", line 139, in build
    self._build_config()
  File "/home/linux/llvm-toolchain/toolchain/llvm_android/base_builders.py", line 424, in _build_config
    utils.check_call(ninja_cmd, cwd=self.output_dir, env=env)
  File "/home/linux/llvm-toolchain/toolchain/llvm_android/utils.py", line 56, in check_call
    return subprocess_run(cmd, *args, **kwargs, check=True)
  File "/home/linux/llvm-toolchain/toolchain/llvm_android/utils.py", line 46, in subprocess_run
    return subprocess.run(cmd, *args, **kwargs, text=True)
  File "/home/linux/llvm-toolchain/prebuilts/python/linux-x86/lib/python3.9/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/linux/llvm-toolchain/prebuilts/build-tools/linux-x86/bin/ninja']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "toolchain/llvm_android/build.py", line 21, in <module>
    py3_utils.run_with_py3('do_build.py')
  File "/home/linux/llvm-toolchain/toolchain/llvm_android/py3_utils.py", line 35, in run_with_py3
    subprocess.check_call(
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/linux/llvm-toolchain/prebuilts/python/linux-x86/bin/python3', '/home/linux/llvm-toolchain/toolchain/llvm_android/do_build.py', '--no-build', 'linux']' returned non-zero exit status 1.
root@linux-virtual-machine:/home/linux/llvm-toolchain# 
```
